# Custom CSS theme for doxygen HTML-documentation with lots of customization parameters.
FetchContent_Declare(
  DoxygenAwesome
  GIT_REPOSITORY https://github.com/jothepro/doxygen-awesome-css.git
  GIT_TAG        v2.2.1
)

# Enable Doxygen's built-in support for STL classes.
set(DOXYGEN_BUILTIN_STL_SUPPORT YES)

# Generate graphs that show the directory dependencies for every directory.
set(DOXYGEN_DIRECTORY_GRAPH NO)

# Set the image format of the images generated by dot.
set(DOXYGEN_DOT_IMAGE_FORMAT svg)

# Set the path to the examples directory.
set(DOXYGEN_EXAMPLE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/examples/src")

# Exclude symbols from the documentation.
set(DOXYGEN_EXCLUDE_SYMBOLS "detail::*,*::detail::*")

# Generate HTML output.
set(DOXYGEN_GENERATE_HTML YES)

# Use the "dot" tool from graphviz to generate advanced diagrams and graphs
set(DOXYGEN_HAVE_DOT YES)

# Set the format used for rendering formulas in the HTML output.
set(DOXYGEN_HTML_FORMULA_FORMAT svg)

# Set the path to a custom HTML header file.
set(DOXYGEN_HTML_HEADER "${CMAKE_CURRENT_SOURCE_DIR}/docs/doxygen-header.html")

# Set the output directory for the HTML output.
# set(DOXYGEN_HTML_OUTPUT "${CMAKE_CURRENT_SOURCE_DIR}/docs/html")

# Generate an include dependency graph for each documented file.
set(DOXYGEN_INCLUDE_GRAPH NO)

# Generate an included-by graph for each documented file.
set(DOXYGEN_INCLUDED_BY_GRAPH NO)

# Make SVG images interactive by using JavaScript.
set(DOXYGEN_INTERACTIVE_SVG YES)

# Enable or disable PDF hyperlinks in LaTeX output.
set(DOXYGEN_PDF_HYPERLINKS YES)

# Brief description of the project.
set(DOXYGEN_PROJECT_BRIEF "C++17 string manipulation library.")

# Set the path to a project logo image file.
set(DOXYGEN_PROJECT_LOGO "${CMAKE_CURRENT_SOURCE_DIR}/data/logo_74x55.png")

# Repeat brief descriptions in detailed descriptions.
set(DOXYGEN_REPEAT_BRIEF YES)

# Enable or disable use of pdflatex to generate PDF files from LaTeX output.
set(DOXYGEN_USE_PDFLATEX YES)

# Enable or disable verbatim copy of header files for classes with includes.
set(DOXYGEN_VERBATIM_HEADERS NO)

macro(use_doxygen_awesome)
  # Fetch and make available DoxygenAwesome content
  FetchContent_MakeAvailable(DoxygenAwesome)

  # Enable or disable index generation
  set(DOXYGEN_DISABLE_INDEX NO)

  # Enable or disable full sidebar
  set(DOXYGEN_FULL_SIDEBAR NO)

  # Set color style for HTML output
  set(DOXYGEN_HTML_COLORSTYLE LIGHT)

  # Set list of extra files that should be copied to HTML output directory
  set(DOXYGEN_HTML_EXTRA_FILES
    "${doxygenawesome_SOURCE_DIR}/doxygen-awesome-tabs.js"
    "${doxygenawesome_SOURCE_DIR}/doxygen-awesome-paragraph-link.js"
    "${doxygenawesome_SOURCE_DIR}/doxygen-awesome-darkmode-toggle.js"
    "${doxygenawesome_SOURCE_DIR}/doxygen-awesome-interactive-toc.js"
    "${doxygenawesome_SOURCE_DIR}/doxygen-awesome-fragment-copy-button.js"
  )

  # Set path to extra stylesheet for HTML output
  set(DOXYGEN_HTML_EXTRA_STYLESHEET "${doxygenawesome_SOURCE_DIR}/doxygen-awesome.css")
endmacro()

macro(use_doxygen_awesome_sidebar_only_theme)
  # Call macro
  use_doxygen_awesome()

  # Enable treeview generation
  set(DOXYGEN_GENERATE_TREEVIEW YES)

  # Set list of extra stylesheets for HTML output
  set(DOXYGEN_HTML_EXTRA_STYLESHEET
    "${doxygenawesome_SOURCE_DIR}/doxygen-awesome.css"
    "${doxygenawesome_SOURCE_DIR}/doxygen-awesome-sidebar-only.css"
    "${doxygenawesome_SOURCE_DIR}/doxygen-awesome-sidebar-only-darkmode-toggle.css"
  )
endmacro()
